brands = {
    "سامسونگ": "Samsung",
    "ساسونگ": "Samsung",
    "شیائومی": "Xiaomi",
    "اپل": "Apple",
    "هوآوی": "Huawei",
    "نوکیا": "Nokia",
    "آنر": "Honor",
    "موتورولا": "Motorola",
    "جی پلاس": "G Plus",
    "وان پلاس": "OnePlus",
    "جی ال ایکس": "GLX",
    "ای دیتا": "ADATA",
    "دوجی": "DOOGEE",
    "یوسمز": "Usams",
    "مولتی نانو": "Multi Nano",
    "هایسنس": "Hisense",
    "هایلو": "haylou",
    "کیو سی وای": "QCY",
    "ویوو": "Vivo",
    "سونی": "Sony",
    "بلک بری": "BlackBerry",
    "ایسوس": "ASUS",
    " اینفینیکس": "Infinix",
    "ریلمی": "realme",
    "پرووان": "ProOne",
    "میتوبل": "Mietubl",
    "لنوو": "lenovo",
    "آمازفیت": "amazfit",
    "امازفیت": "amazfit",
    "امیزفیت": "amazfit",
    "وان مور": "OneMore",
    "بلو": "Blu",
}