# Generated by Django 3.2.16 on 2023-01-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahmooleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=128, null=True)),
                ('date', models.DateField(null=True)),
                ('mahmoole_type', models.CharField(choices=[('depo', 'depo'), ('order', 'order')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pid',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='mahmoole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.mahmoolemodel'),
        ),
    ]
