# Generated by Django 3.2.16 on 2023-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230107_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='dkpc',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
