# Generated by Django 3.2.16 on 2023-02-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_dkpc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('-mahmoole__date',)},
        ),
    ]
